branch-defaults:
  master:
    environment: Storeapp-env
    group_suffix: null
global:
  application_name: store-app
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: akhilkumarm
  repository: null
  sc: git
  workspace_type: Application
