version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.1.3
  aws-eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-eb/setup
      # - browser-tools/install-chrome
      # - browser-tools/install-chromedriver
      # - run:
      #     command: |
      #       google-chrome --version
      #       chromedriver --version
      #     name: Check install
      - run:
          name: FrontEnd Install
          command: |
            npm run frontend:install
      - run:
          name: Backend Install
          command: |
            npm run backend:install
      - run:
          name: FrontEnd Build
          command: |
            npm run frontend:build
      - run:
          name: BackEnd Build
          command: |
            npm run backend:build
      - run:
          name: Backend Test
          command: |
            npm run backend:test
      - run:
          name: BackEnd Deploy
          command: |
            npm run backend:deploy
      - run:
          name: FrontEnd App Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Done
          command: |
           echo "Deployment Done"
