branch-defaults:
  default:
    environment: Mystoreapp-env
deploy:
  artifact: dist/Archive.zip
environment-defaults:
  Mystoreapp-env:
    branch: null
    repository: null
global:
  application_name: mystoreapp
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  sc: null
  workspace_type: Application
