branch-defaults:
  default:
    environment: Storeapp-env
deploy:
  artifact: ./dist/Archive.zip
environment-defaults:
  Storeapp-env:
    branch: null
    repository: null
global:
  application_name: store-app
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: ebdeploy
  sc: null
  workspace_type: Application
